// ============================================================================
// PDF Common — Shared layout helpers for regulatory-grade report PDFs
// ============================================================================

import jsPDF from "jspdf"

// Brand colors
export const NAVY = "#0f172a"
export const GOLD = "#d4a017"
export const DARK_GRAY = "#374151"
export const MED_GRAY = "#6b7280"
export const LIGHT_GRAY = "#e5e7eb"
export const RED = "#dc2626"
export const AMBER = "#d97706"
export const GREEN = "#16a34a"

export function createDoc(): jsPDF {
  return new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" })
}

/** Standard header block for all vendor reports */
export function drawHeader(doc: jsPDF, opts: {
  title: string
  subtitle?: string
  dateLabel?: string
  pageWidth: number
}) {
  const { title, subtitle, dateLabel, pageWidth } = opts
  const margin = 40

  // Gold top rule
  doc.setDrawColor(GOLD)
  doc.setLineWidth(3)
  doc.line(margin, 36, pageWidth - margin, 36)

  // Title
  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.setTextColor(NAVY)
  doc.text(title, margin, 58)

  // Subtitle
  let y = 62
  if (subtitle) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    doc.setTextColor(MED_GRAY)
    doc.text(subtitle, margin, y + 14)
    y += 14
  }

  // Date label
  if (dateLabel) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    doc.setTextColor(MED_GRAY)
    doc.text(dateLabel, pageWidth - margin, 58, { align: "right" })
  }

  // Organization
  doc.setFontSize(8)
  doc.setTextColor(GOLD)
  doc.text("SkyShare MX — Maintenance Vendor Management", pageWidth - margin, y + 14, { align: "right" })
  y += 14

  // Rule under header
  doc.setDrawColor(LIGHT_GRAY)
  doc.setLineWidth(0.5)
  doc.line(margin, y + 8, pageWidth - margin, y + 8)

  return y + 20
}

/** Standard footer on each page */
export function drawFooter(doc: jsPDF, opts: {
  pageNum: number
  totalPages: number
  pageWidth: number
  pageHeight: number
  generatedBy: string
}) {
  const { pageNum, totalPages, pageWidth, pageHeight, generatedBy } = opts
  const margin = 40
  const y = pageHeight - 30

  doc.setDrawColor(LIGHT_GRAY)
  doc.setLineWidth(0.5)
  doc.line(margin, y - 8, pageWidth - margin, y - 8)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(7)
  doc.setTextColor(MED_GRAY)
  doc.text(`Generated by ${generatedBy} on ${new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit",
  })}`, margin, y)
  doc.text(
    `Page ${pageNum} of ${totalPages}`,
    pageWidth - margin,
    y,
    { align: "right" },
  )

  doc.setFontSize(6)
  doc.setTextColor(GOLD)
  doc.text("CONFIDENTIAL — SkyShare MX Vendor Compliance Record", pageWidth / 2, y + 10, { align: "center" })
}

/** Section header bar */
export function drawSectionHeader(doc: jsPDF, text: string, y: number, pageWidth: number): number {
  const margin = 40
  doc.setFillColor(NAVY)
  doc.rect(margin, y, pageWidth - margin * 2, 18, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(255, 255, 255)
  doc.text(text, margin + 8, y + 12)
  return y + 24
}

/** Key-value field line */
export function drawField(doc: jsPDF, label: string, value: string, x: number, y: number): number {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(DARK_GRAY)
  doc.text(label + ":", x, y)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(NAVY)
  doc.text(value || "—", x + 120, y)
  return y + 13
}

/** Status badge (colored text) */
export function drawStatusBadge(doc: jsPDF, label: string, color: string, x: number, y: number) {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(color)
  doc.text(label, x, y)
}

/** Check if we need a page break, return new Y or add page */
export function ensureSpace(doc: jsPDF, y: number, needed: number, pageHeight: number): number {
  if (y + needed > pageHeight - 50) {
    doc.addPage()
    return 50
  }
  return y
}
