import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const supabase = createClient(
  Deno.env.get("SUPABASE_URL") || "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "",
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface UserInvitationRequest {
  email: string;
  firstName: string;
  lastName: string;
  role: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  let invitationId;
  
  try {
    const { email, firstName, lastName, role }: UserInvitationRequest = await req.json();

    // First, create an invitation record in the database
    const { data: invitation, error: inviteError } = await supabase
      .from('user_invitations')
      .insert({
        email,
        first_name: firstName,
        last_name: lastName,
        role,
        status: 'Pending',
        invited_by: null // Service role can bypass RLS
      })
      .select()
      .single();

    if (inviteError) {
      console.error("Error creating invitation:", inviteError);
      throw new Error(`Failed to create invitation: ${inviteError.message}`);
    }

    invitationId = invitation.id;

    // Try sending email with primary sender first
    let emailResponse;
    try {
      emailResponse = await resend.emails.send({
        from: "Jonathan @ SkyShare <jonathan@skyshare.com>",
        to: [email],
        subject: "You've been invited to SkyShare Maintenance Portal",
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background-color: #f8f9fa; padding: 12px; border-radius: 4px; margin-bottom: 20px; border-left: 4px solid #6c757d;">
              <p style="margin: 0; font-size: 12px; color: #6c757d;">
                <em>This is an automated message generated by the SkyShare Maintenance Portal system and was not personally typed by Jonathan.</em>
              </p>
            </div>
            
            <h1 style="color: #2563eb; margin-bottom: 20px;">Welcome to SkyShare Maintenance Portal</h1>
            
            <p>Hi ${firstName},</p>
            
            <p>You've been invited to join the SkyShare Maintenance Portal as a <strong>${role}</strong>.</p>
            
            <p>SkyShare Maintenance Portal is your central hub for aircraft maintenance operations and oversight.</p>
            
            <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="margin-top: 0; color: #374151;">Your Account Details:</h3>
              <ul style="color: #6b7280;">
                <li><strong>Email:</strong> ${email}</li>
                <li><strong>Role:</strong> ${role}</li>
              </ul>
            </div>
            
            <p>To get started, please visit the portal and use your email address to sign in:</p>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${Deno.env.get("SITE_URL") || "https://skyshare-maintenance.lovable.app"}/login" 
                 style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
                Access SkyShare Portal
              </a>
            </div>
            
            <p>If you have any questions or need assistance, please don't hesitate to reach out to your administrator.</p>
            
            <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
            
            <p style="color: #6b7280; font-size: 14px;">
              This invitation was sent from SkyShare Maintenance Portal. If you received this email in error, please ignore it.
            </p>
          </div>
        `,
      });

      // If primary sender fails due to domain verification, try fallback
      if (emailResponse.error && emailResponse.error.message?.includes('domain is not verified')) {
        console.log("Primary domain failed, trying fallback sender...");
        emailResponse = await resend.emails.send({
          from: "SkyShare Maintenance Portal <onboarding@resend.dev>",
          to: [email],
          subject: "You've been invited to SkyShare Maintenance Portal",
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background-color: #f8f9fa; padding: 12px; border-radius: 4px; margin-bottom: 20px; border-left: 4px solid #6c757d;">
                <p style="margin: 0; font-size: 12px; color: #6c757d;">
                  <em>This is an automated message generated by the SkyShare Maintenance Portal system and was not personally typed by Jonathan.</em>
                </p>
              </div>
              
              <h1 style="color: #2563eb; margin-bottom: 20px;">Welcome to SkyShare Maintenance Portal</h1>
              
              <p>Hi ${firstName},</p>
              
              <p>You've been invited by Jonathan @ SkyShare to join the SkyShare Maintenance Portal as a <strong>${role}</strong>.</p>
              
              <p>SkyShare Maintenance Portal is your central hub for aircraft maintenance operations and oversight.</p>
              
              <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="margin-top: 0; color: #374151;">Your Account Details:</h3>
                <ul style="color: #6b7280;">
                  <li><strong>Email:</strong> ${email}</li>
                  <li><strong>Role:</strong> ${role}</li>
                </ul>
              </div>
              
              <p>To get started, please visit the portal and use your email address to sign in:</p>
              
              <div style="text-align: center; margin: 30px 0;">
                <a href="${Deno.env.get("SITE_URL") || "https://skyshare-maintenance.lovable.app"}/login" 
                   style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
                  Access SkyShare Portal
                </a>
              </div>
              
              <p>If you have any questions or need assistance, please don't hesitate to reach out to your administrator.</p>
              
              <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
              
              <p style="color: #6b7280; font-size: 14px;">
                This invitation was sent from SkyShare Maintenance Portal. If you received this email in error, please ignore it.
              </p>
            </div>
          `,
        });
      }
    } catch (emailError: any) {
      console.error("Email sending failed:", emailError);
      
      // Update invitation status to Failed
      await supabase
        .from('user_invitations')
        .update({
          status: 'Failed',
          error_message: emailError.message
        })
        .eq('id', invitationId);

      throw emailError;
    }

    // If we have an error in the response, handle it
    if (emailResponse.error) {
      console.error("Email response error:", emailResponse.error);
      
      // Update invitation status to Failed
      await supabase
        .from('user_invitations')
        .update({
          status: 'Failed',
          error_message: emailResponse.error.message
        })
        .eq('id', invitationId);

      throw new Error(emailResponse.error.message);
    }

    // Update invitation status to Sent
    await supabase
      .from('user_invitations')
      .update({
        status: 'Sent',
        sent_at: new Date().toISOString()
      })
      .eq('id', invitationId);

    console.log("Invitation email sent successfully:", emailResponse);

    return new Response(JSON.stringify({
      success: true,
      invitation_id: invitationId,
      email_response: emailResponse
    }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-user-invitation function:", error);
    
    // If we have an invitation ID, update its status to Failed
    if (invitationId) {
      try {
        await supabase
          .from('user_invitations')
          .update({
            status: 'Failed',
            error_message: error.message
          })
          .eq('id', invitationId);
      } catch (updateError) {
        console.error("Failed to update invitation status:", updateError);
      }
    }
    
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);