-- ─────────────────────────────────────────────────────────────────────────────
-- DW1GHT Playbook Suggestions
-- Section-level playbook edit suggestions generated by:
--   - self-critique (post-interview Sonnet review)
--   - dom_review (DOM feedback path)
--   - ai_assist  (on-demand inline assist from Workbench)
--   - import     (pasted from external AI response)
--
-- review_status: 'pending' | 'accepted' | 'rejected'
-- change_type:   'append' (add new content) | 'replace_section' (full replacement)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS dw1ght_playbook_suggestions (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  playbook_slug  text        NOT NULL,
  section_key    text        NOT NULL,
  -- 'allowed_context' | 'instructions' | 'decision_logic'
  -- 'output_definition' | 'post_processing' | 'tone_calibration'
  change_type    text        NOT NULL DEFAULT 'append',
  -- 'append' — add new content to the section
  -- 'replace_section' — replace the entire section text
  suggested_text text        NOT NULL,
  reasoning      text,
  source_type    text        NOT NULL,
  -- 'self_critique' | 'dom_review' | 'ai_assist' | 'import'
  source_id      uuid,
  -- enrichment_id for self_critique/dom_review; null for ai_assist/import
  review_status  text        NOT NULL DEFAULT 'pending',
  created_at     timestamptz NOT NULL DEFAULT now(),
  reviewed_at    timestamptz,
  reviewed_by    uuid        REFERENCES profiles(id)
);

ALTER TABLE dw1ght_playbook_suggestions ENABLE ROW LEVEL SECURITY;

-- Managers, Admins, and Super Admins can read suggestions
CREATE POLICY "playbook_suggestions_select"
  ON dw1ght_playbook_suggestions
  FOR SELECT
  TO authenticated
  USING (
    is_admin_or_super(auth.uid())
    OR has_role('Manager'::app_role, auth.uid())
  );

-- Admins and Super Admins can insert/update/delete suggestions
CREATE POLICY "playbook_suggestions_write"
  ON dw1ght_playbook_suggestions
  FOR ALL
  TO authenticated
  USING (is_admin_or_super(auth.uid()))
  WITH CHECK (is_admin_or_super(auth.uid()));

-- Service role always has full access (used by Netlify functions)
CREATE POLICY "playbook_suggestions_service_role"
  ON dw1ght_playbook_suggestions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE INDEX IF NOT EXISTS dw1ght_playbook_suggestions_slug_status_idx
  ON dw1ght_playbook_suggestions (playbook_slug, review_status);
