// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const browserEnv = import.meta.env;
const nodeEnv = typeof process !== "undefined" ? process.env : undefined;

// Prefer Vite vars, fallback to NEXT_PUBLIC_ if present
const SUPABASE_URL =
  browserEnv.VITE_SUPABASE_URL ??
  nodeEnv?.NEXT_PUBLIC_SUPABASE_URL ??
  "https://vmxeiyzqzdursrdgenqa.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  browserEnv.VITE_SUPABASE_ANON_KEY ??
  nodeEnv?.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZteGVpeXpxemR1cnNyZGdlbnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzE5NDgsImV4cCI6MjA3MzY0Nzk0OH0.ACwRUfyEYMjJLiF5d-6Dzh1docfp7cywcAn8wx3k93A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
