/**
 * useMatchChunks — vector similarity search over rv_page_chunks.
 *
 * Accepts a pre-computed query embedding (number[1024]) from Voyage AI
 * and returns the top-N most semantically similar chunks with source info.
 *
 * This hook is the retrieval layer for RAG queries against aircraft records.
 * The query embedding must be generated by the caller (typically via a
 * Netlify function that calls Voyage AI so the API key stays server-side).
 *
 * Usage:
 *   const { data: chunks } = useMatchChunks(queryEmbedding, aircraftId)
 */

import { useQuery } from "@tanstack/react-query"
import { supabase } from "@/lib/supabase"
import type { PageChunk } from "../types"

interface MatchChunksParams {
  queryEmbedding: number[] | null   // 1024-dim Voyage AI vector
  aircraftId?: string | null        // null = fleet-wide
  limit?: number
  threshold?: number                // cosine similarity floor, default 0.4
}

export function useMatchChunks({
  queryEmbedding,
  aircraftId,
  limit = 10,
  threshold = 0.4,
}: MatchChunksParams) {
  return useQuery({
    queryKey: ["rv-match-chunks", queryEmbedding?.slice(0, 4), aircraftId, limit, threshold],
    queryFn: async () => {
      const { data, error } = await supabase.rpc("rv_match_chunks", {
        query_embedding: queryEmbedding as unknown as string, // pgvector accepts JSON array
        p_aircraft_id:   aircraftId ?? null,
        p_limit:         limit,
        p_threshold:     threshold,
      })
      if (error) throw error
      return (data ?? []) as PageChunk[]
    },
    enabled: !!queryEmbedding && queryEmbedding.length === 1024,
    staleTime: 2 * 60 * 1000,
  })
}
